//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Player Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerInputGamepad"",
            ""id"": ""a55e407b-3f4b-46c5-84b9-e87eeae91d70"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""d0de6444-ff02-4d9e-a8c7-b9420b6b509f"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93df43a7-3ce1-4e1f-bf61-818771d1a834"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInputGamepad
        m_PlayerInputGamepad = asset.FindActionMap("PlayerInputGamepad", throwIfNotFound: true);
        m_PlayerInputGamepad_Movement = m_PlayerInputGamepad.FindAction("Movement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputGamepad
    private readonly InputActionMap m_PlayerInputGamepad;
    private IPlayerInputGamepadActions m_PlayerInputGamepadActionsCallbackInterface;
    private readonly InputAction m_PlayerInputGamepad_Movement;
    public struct PlayerInputGamepadActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerInputGamepadActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerInputGamepad_Movement;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputGamepad; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputGamepadActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputGamepadActions instance)
        {
            if (m_Wrapper.m_PlayerInputGamepadActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerInputGamepadActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerInputGamepadActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerInputGamepadActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_PlayerInputGamepadActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public PlayerInputGamepadActions @PlayerInputGamepad => new PlayerInputGamepadActions(this);
    public interface IPlayerInputGamepadActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
}
